CORELLIA_CONFIG_FILE = "corellia.toml"
PY_ENV_COMMAND = "pyenv"
GIT_COMMAND = "git"
GIT_AVAILABLE = "initialized"
GIT_NOT_AVAILABLE = "not available"
DEFAULT_VENV_NAME = ".venv"
PM = "pip"

DEPENDENCY_SECTION_NAME = "dependencies"
DEV_DEPENDENCY_SECTION_NAME = "dev-dependencies"
ENVIRONMENT_SECTION_NAME = "environment"
PROJECT_SECTION_NAME = "project"
SCRIPTS_SECTION_NAME = "scripts"
FRAMEWORK_SECTION_NAME = "framework"